services:
  adimeodatasource.filters.concatenatefilter:
    class: AdimeoDataSuite\Bundle\ProcessorsBundle\ProcessorFilter\ProcessorFilter
    public: true
    tags:
      - { name: adimeodatasuite.filter }